apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-efs-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: efs-filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-efs-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: efs-filesystem