apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-efs-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-filesystem
  csi:
    driver: efs.csi.aws.com
    volumeHandle: <your-wordpress-efs-file-system-id>
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-efs-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-filesystem
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-02411a71997d17fdd