apiVersion: v1
kind: Service
metadata:
  labels:
    name: wordpress
  name: wordpress
spec:
  ports:
    - port: 80
  selector:
    name: wordpress
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 2
  selector:
    matchLabels:
      name: wordpress
  template:
    metadata:
      labels:
        name: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - mountPath: /var/www/html
          name: wordpress-ebs-volume
        env:
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wp-db-secrets
              key: MYSQL_ROOT_PASSWORD
        - name: WORDPRESS_DB_USER
          value: wordpress
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
      volumes:
      - name: wordpress-ebs-volume
        persistentVolumeClaim:
          claimName: ebs-mysql-pv-claim