name: Deploy to EKS
on:
  workflow_dispatch
env:
  AWS_REGION: "eu-west-1"
  ENV: "dev"
permissions:
  id-token: write
  contents: read
  issues: write
jobs:
  deployment:
    name: Deploy application to EKS cluster
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.SHIVA_AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.SHIVA_AWS_SECRET_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
    
    - name: Update kube config
      run: |
        aws eks update-kubeconfig --name ekslabcluster --region ${{ env.AWS_REGION }}	
          
    - name: Deploy application images to EKS cluster using manifest
      run: |
        kubectl apply -f storageclass.yaml
        kubectl apply -f pvc.yaml
        kubectl apply -f rds-external-service.yaml
        kubectl apply -f secret.yaml
        kubectl apply -f wordpress-deployment.yaml 