name: Deploy to EKS
on:
  workflow_dispatch
env:
  AWS_REGION: "eu-west-1"
  ENV: "dev"
permissions:
  id-token: write
  contents: read
jobs:
  deployment:
    name: Deploy application to EKS cluster
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout code from GitHub to runner
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.SHIVA_AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.SHIVA_AWS_SECRET_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
        # with:
        #   version: '1.27' # default is latest stable
    - name: Update kube config
      run: |
        aws eks update-kubeconfig --name eks-cluster-L1Ivj --region ${{ env.AWS_REGION }}	
          
    - name: Deploy application images to EKS cluster using manifest
      run: |
        kubectl version --short
        kubectl apply -f efs-storageclass.yml
        kubectl apply -f persistent-volume.yml
        kubectl apply -f persistent-volume-claim.yml
        kubectl apply -f wp-configmap.yml
        kubectl apply -f secret.yml
        kubectl apply -f mysql-deployment.yml
        kubectl apply -f wordpress-deployment.yml 